name: 🧑‍🔧 Tests Private Pools

on:
  schedule:
    - cron: '0 7 * * *' # 8:00 AM CET (UTC+1) / 7:00 AM UTC
    - cron: '0 12 * * *' # 1:00 PM CET (UTC+1) / 12:00 PM UTC
    - cron: '0 20 * * *' # 9:00 PM CET (UTC+1) / 8:00 PM UTC
  push:
    branches:
      - master
      # - main
      # - ivan-dev
  pull_request:
    paths:
      - '.github/actions/**/*.yml'
      - '.github/workflows/**/*.yml'
      - 'packages/**'
      - 'wallets/**'

jobs:
  # test-unit:
  #   name: Run unit tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Node & Install dependencies
  #       uses: ./.github/actions/setup

  #     - name: Playwright install
  #       run: xvfb-run pnpm exec playwright install
  #     - name: Build project
  #       run: pnpm run build

  #     - name: Run tests
  #       run: pnpm run test

  test-e2e-headful:
    name: Run E2E tests (headful)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & Install dependencies
        uses: ./.github/actions/setup

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # For now, we only need Chromium.
      - name: Install Playwright Browsers
        run: yarn playwright install chromium
      - name: Install browsers for Playwright 1
        run: pnpm dlx playwright@1.45.2 install chromium

      - name: Install linux dependencies
        run: |
          sudo apt-get install  -y xvfb libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libatspi2.0-0   libxcomposite1  libxdamage1     libxrandr2     libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2

      - name: Build cache
        run: xvfb-run pnpm run build:cache
        env:
          DEBUG: 'pw:api,synpress:*'
          PLAYWRIGHT_HEADLESS: 'false'
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SEED_PHRASE: ${{ secrets.SEED_PHRASE }}

      - name: Run E2E tests (headful)
        run: |
          xvfb-run pnpm run test:e2e:headful
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SEED_PHRASE: ${{ secrets.SEED_PHRASE }}
          # Created by Vercel CLI
          NODE_ENV: 'development'
          NX_DAEMON: ''
          VERCEL: '1'
          VERCEL_ENV: 'development'
          VERCEL_GIT_COMMIT_AUTHOR_LOGIN: ''
          VERCEL_GIT_COMMIT_AUTHOR_NAME: ''
          VERCEL_GIT_COMMIT_MESSAGE: ''
          VERCEL_GIT_COMMIT_REF: ''
          VERCEL_GIT_COMMIT_SHA: ''
          VERCEL_GIT_PREVIOUS_SHA: ''
          VERCEL_GIT_PROVIDER: ''
          VERCEL_GIT_PULL_REQUEST_ID: ''
          VERCEL_GIT_REPO_ID: ''
          VERCEL_GIT_REPO_OWNER: ''
          VERCEL_GIT_REPO_SLUG: ''
          VERCEL_URL: ''
          VUE_APP_1INCHEXECUTOR_CONTRACT_BINANCE: '0xE37e799D5077682FA0a244D46E5649F71457BD09'
          VUE_APP_ARBITRAGE_WALLET: '0x67B27D5D938eE384917cfE5e2F1faee530468475'
          VUE_APP_AUSD_BINANCE: ''
          VUE_APP_AUTHORIZER_BINANCE: '0x04c31002FBC993c70F2b8b83b1AfE0410bDA6680'
          VUE_APP_BACKEND_URL_BINANCE: 'https://privatepools-sharedversion-backend.xyz/graphql'
          VUE_APP_BALANCER_HELPERS_BINANCE: '0x6D498379211811F9b8090709efE10af7f6A1F0AF'
          VUE_APP_BATCH_RELAYER_BINANCE: '0xD98056C33c1Ab67F6Dc1C7487AfB99824a7F464E'
          VUE_APP_BLOCK_SUBGRAPH_BINANCE: 'https://gateway.thegraph.com/api/c4373604f01ecf5f72cfe13743bd2329/subgraphs/id/E1RLMz7rnB8YHjUqeAvA962HrJPuyn3iLHS6MLxBn9GW'
          VUE_APP_BOT_BINANCE: 'https://binancerunbotdoprimocosta.xyz'
          VUE_APP_BOT_LOGS_BINANCE: 'wss://binancerunbotdoprimocosta.xyz'
          VUE_APP_B_ACTIONS_BINANCE: ''
          VUE_APP_B_FACTORY_BINANCE: ''
          VUE_APP_CHAIN_ID_BINANCE: '56'
          VUE_APP_CHAIN_NAME_BINANCE: 'Binance'
          VUE_APP_COINGECKO_API_KEY: ''
          VUE_APP_COMPOUNDER_CONTRACT_BINANCE: '0xf1addaccc4814b8ea847d0d75e261784e48ccda0'
          VUE_APP_CONFIG_SANITY_URL_BINANCE: 'https://raw.githubusercontent.com/chimpytuts/darkpools-vault-subgraph/binance/assets/pairList.json'
          VUE_APP_COPPER_PROXY_BINANCE: ''
          VUE_APP_CRYPTOCOMPARE_API_KEY: '818f9c16d8ddb052e87416d157cc013570cda21b5cd4212c419adffacea92a4e'
          VUE_APP_CRYPTOCOMPARE_BY_DEFAULT: 'true'
          VUE_APP_DEFAULT_POOL_OWNER_BINANCE: ''
          VUE_APP_DS_PROXY_REGISTRY_BINANCE: ''
          VUE_APP_EARLY_LUDWIG_NFT_BINANCE: ''
          VUE_APP_EMBR_BINANCE: ''
          VUE_APP_EMBR_TOKEN_BINANCE: ''
          VUE_APP_EMBR_USDC_REFERENCE_PRICE_POOL_BINANCE: ''
          VUE_APP_ETHERSCAN_API_KEY_BINANCE: ''
          VUE_APP_ETHERSCAN_API_URL_BINANCE: ''
          VUE_APP_EXCHANGE_PROXY_BINANCE: ''
          VUE_APP_EXPLORER_BINANCE: 'https://bscscan.com'
          VUE_APP_EXPLORER_NAME_BINANCE: 'Binance Explorer'
          VUE_APP_FARM_SUBGRAPH_BINANCE: ''
          VUE_APP_HND_BINANCE: ''
          VUE_APP_HND_REWARDER_BINANCE: ''
          VUE_APP_KEY_BINANCE: '56'
          VUE_APP_LIDO_RELAYER_BINANCE: ''
          VUE_APP_LOCAL_API: 'true'
          VUE_APP_LOGGING_RPC_BINANCE: ''
          VUE_APP_MASTER_CHEF_BINANCE: '0xE2CbAa8922fBBF2BA829E97a657E917B59C343C0'
          VUE_APP_MERKLE_ORCHARD_BINANCE: ''
          VUE_APP_MERKLE_REDEEM_BINANCE: ''
          VUE_APP_MULTICALL_BINANCE: '0x0BE16f83d08152974b61F914dF68033789E115D6'
          VUE_APP_NAME_BINANCE: 'Binance'
          VUE_APP_NETWORK_BINANCE: 'binance-smart-chain'
          VUE_APP_OPPORTUNITIES_BINANCE: ''
          VUE_APP_OPPORTUNITIES_PASSWORD: ''
          VUE_APP_OPPORTUNITIES_USER: ''
          VUE_APP_OUTPUT_LINK_BINANCE: 'https://privatepools-env2-vault.xyz'
          VUE_APP_POOLS_URL_V1_BINANCE: ''
          VUE_APP_POOLS_URL_V2_BINANCE: ''
          VUE_APP_REDUNDANT_OUTPUT_LINK_BINANCE: 'https://privatepools-env3-vault.xyz'
          VUE_APP_REDUNDANT_REWARDS_BACKEND_BINANCE: ''
          VUE_APP_REWARDS_BACKEND_BINANCE: 'https://client2-csv-polygond3.xyz'
          VUE_APP_REWARDS_CONTRACT_BINANCE: '0xfad4f78ddc184ba6e0936521d2e9d2bb13587c6b'
          VUE_APP_RPC_BINANCE: 'https://bsc-dataseed.binance.org/'
          VUE_APP_SHORT_NAME_BINANCE: 'Binance'
          VUE_APP_STABLE_POOL_FACTORY_BINANCE: ''
          VUE_APP_STATUS_LINK: 'https://privatepools-check-status.vercel.app/fetch'
          VUE_APP_STETH_BINANCE: ''
          VUE_APP_SUBGRAPH_BINANCE: 'https://gateway.thegraph.com/api/c4373604f01ecf5f72cfe13743bd2329/subgraphs/id/E1RLMz7rnB8YHjUqeAvA962HrJPuyn3iLHS6MLxBn9GW'
          VUE_APP_SUPPORTS_EIP1559_BINANCE: 'false'
          VUE_APP_SUPPORTS_ELEMENT_POOLS_BINANCE: 'false'
          VUE_APP_TOKEN_FACTORY_BINANCE: ''
          VUE_APP_TOKEN_LIST_SANITY_URL_BINANCE: 'https://raw.githubusercontent.com/chimpytuts/darkpools-vault-subgraph/binance/assets/tokenList.json'
          VUE_APP_USDC_BINANCE: '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d'
          VUE_APP_VAULT_BINANCE: '0xB3b7aA353F59f31aBB592455DeaA89a5dD4BC554'
          VUE_APP_WEIGHTED_POOL_FACTORY_BINANCE: '0xf1cC405c16cc10Ce79fE564F83ee7516146B00D4'
          VUE_APP_WETH_BINANCE: '0xbb4CdB9CBd36b01bD1cBaEBF2De08d9173bc095c'
          VUE_APP_WSTETH_BINANCE: ''
          VUE_APP_WS_BINANCE: 'wss://ws-api.binance.com:443/ws-api/v3'
          VUE_APP_XEMBR_ADDRESS_BINANCE: ''
          VUE_APP_XEMBR_POOL_ADDRESS_BINANCE: ''
          VUE_APP_XEMBR_POOL_ID_BINANCE: ''
          VUE_APP_XEMBR_SUBGRAPH_BINANCE: ''
          VUE_APP_XEMBR_TOKEN_BINANCE: ''
          VUE_APP_XEMBR_VESTING_TOKEN_BINANCE: ''
          VUE_APP_ZAP_CONTRACT_BINANCE: '0xc4d1b4b8798cfacce4cc77d53244580d5ace5a1a'
          WAVELENGTH_SDK_SOURCE: 'github:chimpytuts/balancer-sdk-main#client1'
          WAVELENGTH_SOR2_SOURCE: 'github:chimpytuts/balancer-sor#client1'

      # - name: Archive Playwright report
      #   uses: actions/upload-artifact@v3
      #   if: success() || failure()
      #   with:
      #     name: playwright-report-headful
      #     path: |
      #       wallets/metamask/playwright-report-headful/
      #     if-no-files-found: error

  success-notification:
    name: Notify success on Telegram
    needs: test-e2e-headful
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install axios -f
      - name: Send Telegram notification on success
        env:
          TELEGRAM_SERVER_URL: https://privatepools-telegram-bot.vercel.app/send
        run: |
          node sendNotification.mjs --group "d3" --message "Tests passed successfully!"

  # failure-notification:
  #   name: Notify failure on Telegram
  #   needs: test-e2e-headful
  #   if: ${{ failure() }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'
  #     - name: Install dependencies
  #       run: npm install axios -f
  #     - name: Send Telegram notification
  #       env:
  #         TELEGRAM_SERVER_URL: https://privatepools-telegram-bot.vercel.app/send
  #       run: |
  #         node sendNotification.mjs --group "d3" --message "Tests failed! Please check the logs."
